#!/usr/bin/env sh
set -eu

# Git provides ref updates to pre-push on STDIN. If we pass that STDIN through to cmd.exe,
# cmd.exe will try to execute lines like "refs/heads/main ..." as commands.
# Redirect STDIN to NUL to prevent the noise on Windows.
cmd.exe /q /c .githooks\\pre-push.cmd < NUL