using System.Text.Json.Serialization;

namespace SimCore.Entities;

// GATE.T42.PLANET_SCAN.MODEL.001: Scanner enums + scan result entity.

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ScanMode
{
    MineralSurvey = 0,   // Default mode — optimized for Resource Intel
    SignalSweep = 1,     // Mk1+ — optimized for Signal Leads
    Archaeological = 2,  // Mk2+ — optimized for Physical Evidence + Data Archives
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ScanPhase
{
    Orbital = 0,
    Landing = 1,
    AtmosphericSample = 2,  // Gaseous-only deep scan
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum FindingCategory
{
    ResourceIntel = 0,      // Generates TradeRouteIntel
    SignalLead = 1,         // Breadcrumb pointing to another discovery
    PhysicalEvidence = 2,   // Ruins/fossils/installations — investigatable
    FragmentCache = 3,      // Adaptation Fragment drop (landing only)
    DataArchive = 4,        // KnowledgeGraph data log (landing only)
}

// GATE.T42.PLANET_SCAN.MODEL.001: Individual scan result stored in SimState.PlanetScanResults.
public sealed class PlanetScanResult
{
    [JsonInclude] public string ScanId { get; set; } = "";
    [JsonInclude] public string NodeId { get; set; } = "";
    [JsonInclude] public ScanMode Mode { get; set; } = ScanMode.MineralSurvey;
    [JsonInclude] public ScanPhase Phase { get; set; } = ScanPhase.Orbital;
    [JsonInclude] public FindingCategory Category { get; set; } = FindingCategory.ResourceIntel;

    // Discovery ID generated by this scan (empty if none — e.g. FragmentCache goes direct).
    [JsonInclude] public string DiscoveryId { get; set; } = "";

    // Flavor text describing what the player sees.
    [JsonInclude] public string FlavorText { get; set; } = "";

    // Hint line suggesting what a different mode might find (orbital only).
    [JsonInclude] public string HintText { get; set; } = "";

    // Tick when scan was performed.
    [JsonInclude] public int Tick { get; set; }

    // Physical Evidence: can be investigated for bonus KG connections.
    [JsonInclude] public bool InvestigationAvailable { get; set; }
    [JsonInclude] public bool Investigated { get; set; }

    // Fragment ID if this scan dropped a fragment (FragmentCache only).
    [JsonInclude] public string FragmentId { get; set; } = "";

    // Affinity score that produced this result (for diagnostics/FO commentary).
    [JsonInclude] public int AffinityBps { get; set; }
}
